import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/recipes/accordion.ts",
    "src/recipes/alert.ts",
    "src/recipes/alert-dialog.ts",
    "src/recipes/aspect-ratio.ts",
    "src/recipes/avatar.ts",
    "src/recipes/breadcrumb.ts",
    "src/recipes/badge.ts",
    "src/recipes/button.ts",
    "src/recipes/card.ts",
    "src/recipes/carousel.ts",
    "src/recipes/checkbox.ts",
    "src/recipes/collapsible.ts",
    "src/recipes/combobox.ts",
    "src/recipes/color-picker.ts",
    "src/recipes/date-picker.ts",
    "src/recipes/dialog.ts",
    "src/recipes/drawer.ts",
    "src/recipes/hover-card.ts",
    "src/recipes/input.ts",
    "src/recipes/label.ts",
    "src/recipes/listbox.ts",
    "src/recipes/menu.ts",
    "src/recipes/number-input.ts",
    "src/recipes/pagination.ts",
    "src/recipes/password-input.ts",
    "src/recipes/pin-input.ts",
    "src/recipes/popover.ts",
    "src/recipes/progress.ts",
    "src/recipes/radio-group.ts",
    "src/recipes/rating-group.ts",
    "src/recipes/scroll-area.ts",
    "src/recipes/segment-group.ts",
    "src/recipes/select.ts",
    "src/recipes/separator.ts",
    "src/recipes/skeleton.ts",
    "src/recipes/slider.ts",
    "src/recipes/spinner.ts",
    "src/recipes/switch.ts",
    "src/recipes/table.ts",
    "src/recipes/tabs.ts",
    "src/recipes/tags-input.ts",
    "src/recipes/textarea.ts",
    "src/recipes/time-picker.ts",
    "src/recipes/toast.ts",
    "src/recipes/toggle.ts",
    "src/recipes/toggle-group.ts",
    "src/recipes/tooltip.ts",
    "src/recipes/typography.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["tailwind-variants"],
});
