/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsTypographyRouteImport } from './routes/components/typography'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as ComponentsToggleGroupRouteImport } from './routes/components/toggle-group'
import { Route as ComponentsToggleRouteImport } from './routes/components/toggle'
import { Route as ComponentsToastRouteImport } from './routes/components/toast'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsTagsInputRouteImport } from './routes/components/tags-input'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTableRouteImport } from './routes/components/table'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSegmentGroupRouteImport } from './routes/components/segment-group'
import { Route as ComponentsScrollAreaRouteImport } from './routes/components/scroll-area'
import { Route as ComponentsRatingGroupRouteImport } from './routes/components/rating-group'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsProgressRouteImport } from './routes/components/progress'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsPinInputRouteImport } from './routes/components/pin-input'
import { Route as ComponentsPasswordInputRouteImport } from './routes/components/password-input'
import { Route as ComponentsPaginationRouteImport } from './routes/components/pagination'
import { Route as ComponentsNumberInputRouteImport } from './routes/components/number-input'
import { Route as ComponentsMenuRouteImport } from './routes/components/menu'
import { Route as ComponentsListboxRouteImport } from './routes/components/listbox'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsHoverCardRouteImport } from './routes/components/hover-card'
import { Route as ComponentsDrawerRouteImport } from './routes/components/drawer'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsComboboxRouteImport } from './routes/components/combobox'
import { Route as ComponentsColorPickerRouteImport } from './routes/components/color-picker'
import { Route as ComponentsCollapsibleRouteImport } from './routes/components/collapsible'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsCarouselRouteImport } from './routes/components/carousel'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBreadcrumbRouteImport } from './routes/components/breadcrumb'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsAspectRatioRouteImport } from './routes/components/aspect-ratio'
import { Route as ComponentsAlertDialogRouteImport } from './routes/components/alert-dialog'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'

const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTypographyRoute = ComponentsTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsToggleGroupRoute = ComponentsToggleGroupRouteImport.update({
  id: '/toggle-group',
  path: '/toggle-group',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsToggleRoute = ComponentsToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsToastRoute = ComponentsToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/textarea',
  path: '/textarea',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTagsInputRoute = ComponentsTagsInputRouteImport.update({
  id: '/tags-input',
  path: '/tags-input',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/separator',
  path: '/separator',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSegmentGroupRoute = ComponentsSegmentGroupRouteImport.update({
  id: '/segment-group',
  path: '/segment-group',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsScrollAreaRoute = ComponentsScrollAreaRouteImport.update({
  id: '/scroll-area',
  path: '/scroll-area',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsRatingGroupRoute = ComponentsRatingGroupRouteImport.update({
  id: '/rating-group',
  path: '/rating-group',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/radio-group',
  path: '/radio-group',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsProgressRoute = ComponentsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPinInputRoute = ComponentsPinInputRouteImport.update({
  id: '/pin-input',
  path: '/pin-input',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPasswordInputRoute = ComponentsPasswordInputRouteImport.update({
  id: '/password-input',
  path: '/password-input',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPaginationRoute = ComponentsPaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsNumberInputRoute = ComponentsNumberInputRouteImport.update({
  id: '/number-input',
  path: '/number-input',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsListboxRoute = ComponentsListboxRouteImport.update({
  id: '/listbox',
  path: '/listbox',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsHoverCardRoute = ComponentsHoverCardRouteImport.update({
  id: '/hover-card',
  path: '/hover-card',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsDrawerRoute = ComponentsDrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/date-picker',
  path: '/date-picker',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsComboboxRoute = ComponentsComboboxRouteImport.update({
  id: '/combobox',
  path: '/combobox',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsColorPickerRoute = ComponentsColorPickerRouteImport.update({
  id: '/color-picker',
  path: '/color-picker',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCollapsibleRoute = ComponentsCollapsibleRouteImport.update({
  id: '/collapsible',
  path: '/collapsible',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCarouselRoute = ComponentsCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsBreadcrumbRoute = ComponentsBreadcrumbRouteImport.update({
  id: '/breadcrumb',
  path: '/breadcrumb',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsAspectRatioRoute = ComponentsAspectRatioRouteImport.update({
  id: '/aspect-ratio',
  path: '/aspect-ratio',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsAlertDialogRoute = ComponentsAlertDialogRouteImport.update({
  id: '/alert-dialog',
  path: '/alert-dialog',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/color-picker': typeof ComponentsColorPickerRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/listbox': typeof ComponentsListboxRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/number-input': typeof ComponentsNumberInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/password-input': typeof ComponentsPasswordInputRoute
  '/components/pin-input': typeof ComponentsPinInputRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/rating-group': typeof ComponentsRatingGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/segment-group': typeof ComponentsSegmentGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tags-input': typeof ComponentsTagsInputRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/color-picker': typeof ComponentsColorPickerRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/listbox': typeof ComponentsListboxRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/number-input': typeof ComponentsNumberInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/password-input': typeof ComponentsPasswordInputRoute
  '/components/pin-input': typeof ComponentsPinInputRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/rating-group': typeof ComponentsRatingGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/segment-group': typeof ComponentsSegmentGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tags-input': typeof ComponentsTagsInputRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/color-picker': typeof ComponentsColorPickerRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/listbox': typeof ComponentsListboxRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/number-input': typeof ComponentsNumberInputRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/password-input': typeof ComponentsPasswordInputRoute
  '/components/pin-input': typeof ComponentsPinInputRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/rating-group': typeof ComponentsRatingGroupRoute
  '/components/scroll-area': typeof ComponentsScrollAreaRoute
  '/components/segment-group': typeof ComponentsSegmentGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tags-input': typeof ComponentsTagsInputRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/components'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/color-picker'
    | '/components/combobox'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/hover-card'
    | '/components/input'
    | '/components/listbox'
    | '/components/menu'
    | '/components/number-input'
    | '/components/pagination'
    | '/components/password-input'
    | '/components/pin-input'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/rating-group'
    | '/components/scroll-area'
    | '/components/segment-group'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/tags-input'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/components/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/components'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/color-picker'
    | '/components/combobox'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/hover-card'
    | '/components/input'
    | '/components/listbox'
    | '/components/menu'
    | '/components/number-input'
    | '/components/pagination'
    | '/components/password-input'
    | '/components/pin-input'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/rating-group'
    | '/components/scroll-area'
    | '/components/segment-group'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/tags-input'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/components/typography'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/components'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/color-picker'
    | '/components/combobox'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/hover-card'
    | '/components/input'
    | '/components/listbox'
    | '/components/menu'
    | '/components/number-input'
    | '/components/pagination'
    | '/components/password-input'
    | '/components/pin-input'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/rating-group'
    | '/components/scroll-area'
    | '/components/segment-group'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/tags-input'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/components/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/typography': {
      id: '/components/typography'
      path: '/typography'
      fullPath: '/components/typography'
      preLoaderRoute: typeof ComponentsTypographyRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/toggle-group': {
      id: '/components/toggle-group'
      path: '/toggle-group'
      fullPath: '/components/toggle-group'
      preLoaderRoute: typeof ComponentsToggleGroupRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/toggle': {
      id: '/components/toggle'
      path: '/toggle'
      fullPath: '/components/toggle'
      preLoaderRoute: typeof ComponentsToggleRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/tags-input': {
      id: '/components/tags-input'
      path: '/tags-input'
      fullPath: '/components/tags-input'
      preLoaderRoute: typeof ComponentsTagsInputRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/table': {
      id: '/components/table'
      path: '/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/select': {
      id: '/components/select'
      path: '/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/segment-group': {
      id: '/components/segment-group'
      path: '/segment-group'
      fullPath: '/components/segment-group'
      preLoaderRoute: typeof ComponentsSegmentGroupRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/scroll-area': {
      id: '/components/scroll-area'
      path: '/scroll-area'
      fullPath: '/components/scroll-area'
      preLoaderRoute: typeof ComponentsScrollAreaRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/rating-group': {
      id: '/components/rating-group'
      path: '/rating-group'
      fullPath: '/components/rating-group'
      preLoaderRoute: typeof ComponentsRatingGroupRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/pin-input': {
      id: '/components/pin-input'
      path: '/pin-input'
      fullPath: '/components/pin-input'
      preLoaderRoute: typeof ComponentsPinInputRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/password-input': {
      id: '/components/password-input'
      path: '/password-input'
      fullPath: '/components/password-input'
      preLoaderRoute: typeof ComponentsPasswordInputRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/pagination': {
      id: '/components/pagination'
      path: '/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/number-input': {
      id: '/components/number-input'
      path: '/number-input'
      fullPath: '/components/number-input'
      preLoaderRoute: typeof ComponentsNumberInputRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/listbox': {
      id: '/components/listbox'
      path: '/listbox'
      fullPath: '/components/listbox'
      preLoaderRoute: typeof ComponentsListboxRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/hover-card': {
      id: '/components/hover-card'
      path: '/hover-card'
      fullPath: '/components/hover-card'
      preLoaderRoute: typeof ComponentsHoverCardRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/drawer': {
      id: '/components/drawer'
      path: '/drawer'
      fullPath: '/components/drawer'
      preLoaderRoute: typeof ComponentsDrawerRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/combobox': {
      id: '/components/combobox'
      path: '/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/color-picker': {
      id: '/components/color-picker'
      path: '/color-picker'
      fullPath: '/components/color-picker'
      preLoaderRoute: typeof ComponentsColorPickerRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/collapsible': {
      id: '/components/collapsible'
      path: '/collapsible'
      fullPath: '/components/collapsible'
      preLoaderRoute: typeof ComponentsCollapsibleRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/carousel': {
      id: '/components/carousel'
      path: '/carousel'
      fullPath: '/components/carousel'
      preLoaderRoute: typeof ComponentsCarouselRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/card': {
      id: '/components/card'
      path: '/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/breadcrumb': {
      id: '/components/breadcrumb'
      path: '/breadcrumb'
      fullPath: '/components/breadcrumb'
      preLoaderRoute: typeof ComponentsBreadcrumbRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/aspect-ratio': {
      id: '/components/aspect-ratio'
      path: '/aspect-ratio'
      fullPath: '/components/aspect-ratio'
      preLoaderRoute: typeof ComponentsAspectRatioRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/alert-dialog': {
      id: '/components/alert-dialog'
      path: '/alert-dialog'
      fullPath: '/components/alert-dialog'
      preLoaderRoute: typeof ComponentsAlertDialogRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAlertDialogRoute: typeof ComponentsAlertDialogRoute
  ComponentsAspectRatioRoute: typeof ComponentsAspectRatioRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBreadcrumbRoute: typeof ComponentsBreadcrumbRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsCarouselRoute: typeof ComponentsCarouselRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsCollapsibleRoute: typeof ComponentsCollapsibleRoute
  ComponentsColorPickerRoute: typeof ComponentsColorPickerRoute
  ComponentsComboboxRoute: typeof ComponentsComboboxRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDrawerRoute: typeof ComponentsDrawerRoute
  ComponentsHoverCardRoute: typeof ComponentsHoverCardRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsListboxRoute: typeof ComponentsListboxRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsNumberInputRoute: typeof ComponentsNumberInputRoute
  ComponentsPaginationRoute: typeof ComponentsPaginationRoute
  ComponentsPasswordInputRoute: typeof ComponentsPasswordInputRoute
  ComponentsPinInputRoute: typeof ComponentsPinInputRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsProgressRoute: typeof ComponentsProgressRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsRatingGroupRoute: typeof ComponentsRatingGroupRoute
  ComponentsScrollAreaRoute: typeof ComponentsScrollAreaRoute
  ComponentsSegmentGroupRoute: typeof ComponentsSegmentGroupRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTagsInputRoute: typeof ComponentsTagsInputRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsToastRoute: typeof ComponentsToastRoute
  ComponentsToggleRoute: typeof ComponentsToggleRoute
  ComponentsToggleGroupRoute: typeof ComponentsToggleGroupRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsTypographyRoute: typeof ComponentsTypographyRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAlertDialogRoute: ComponentsAlertDialogRoute,
  ComponentsAspectRatioRoute: ComponentsAspectRatioRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBreadcrumbRoute: ComponentsBreadcrumbRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsCarouselRoute: ComponentsCarouselRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsCollapsibleRoute: ComponentsCollapsibleRoute,
  ComponentsColorPickerRoute: ComponentsColorPickerRoute,
  ComponentsComboboxRoute: ComponentsComboboxRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDrawerRoute: ComponentsDrawerRoute,
  ComponentsHoverCardRoute: ComponentsHoverCardRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsListboxRoute: ComponentsListboxRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsNumberInputRoute: ComponentsNumberInputRoute,
  ComponentsPaginationRoute: ComponentsPaginationRoute,
  ComponentsPasswordInputRoute: ComponentsPasswordInputRoute,
  ComponentsPinInputRoute: ComponentsPinInputRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsProgressRoute: ComponentsProgressRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsRatingGroupRoute: ComponentsRatingGroupRoute,
  ComponentsScrollAreaRoute: ComponentsScrollAreaRoute,
  ComponentsSegmentGroupRoute: ComponentsSegmentGroupRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTagsInputRoute: ComponentsTagsInputRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsToastRoute: ComponentsToastRoute,
  ComponentsToggleRoute: ComponentsToggleRoute,
  ComponentsToggleGroupRoute: ComponentsToggleGroupRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsTypographyRoute: ComponentsTypographyRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
