/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsQuickstartRouteImport } from './routes/components/quickstart'
import { Route as ComponentsComponentRouteImport } from './routes/components/$component'

const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsQuickstartRoute = ComponentsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsComponentRoute = ComponentsComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/$component': typeof ComponentsComponentRoute
  '/components/quickstart': typeof ComponentsQuickstartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/$component': typeof ComponentsComponentRoute
  '/components/quickstart': typeof ComponentsQuickstartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/$component': typeof ComponentsComponentRoute
  '/components/quickstart': typeof ComponentsQuickstartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/components'
    | '/components/$component'
    | '/components/quickstart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/components'
    | '/components/$component'
    | '/components/quickstart'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/components'
    | '/components/$component'
    | '/components/quickstart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/quickstart': {
      id: '/components/quickstart'
      path: '/quickstart'
      fullPath: '/components/quickstart'
      preLoaderRoute: typeof ComponentsQuickstartRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/$component': {
      id: '/components/$component'
      path: '/$component'
      fullPath: '/components/$component'
      preLoaderRoute: typeof ComponentsComponentRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsComponentRoute: typeof ComponentsComponentRoute
  ComponentsQuickstartRoute: typeof ComponentsQuickstartRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsComponentRoute: ComponentsComponentRoute,
  ComponentsQuickstartRoute: ComponentsQuickstartRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
